version: '3'

services:
  app:
    image: aamdigital/ndb-server:2.7.1
    networks:
      - internal
      - nginx-proxy_default
    depends_on:
      - couchdb
    volumes:
      - ../../child-photos:/usr/share/nginx/html/assets/child-photos
    restart: unless-stopped

  couchdb:
    image: couchdb
    networks:
      - internal
    volumes:
      - ../../couchdb/data:/opt/couchdb/data
    ports:
      - 5986:5986
    restart: unless-stopped


networks:
  internal:
  nginx-proxy_default:
    external: true
