version: '3'

services:
  app:
    ports:
      - 8080:80
    volumes:
      - ../../env/dev/config.json:/usr/share/nginx/html/assets/config.default.json
  couchdb:
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: PASSWORD

networks:
  internal:
  nginx-proxy_default:
    external: true
